### ISSUE TITLE
Released docker image requires auth

### ISSUE THREAD

**Issue by croomes** [cbws/etcd-operator#39]
First off, thanks for taking the initiative on this.  We rely on etcd and wanted to help improve the operator but were put off by lack of maintenance on the upstream repo.

I just tried switching to the fork in our CI environment but it fails on:
```
$ docker pull docker.pkg.github.com/cbws/etcd-operator/operator:v0.10.0
Error response from daemon: Get https://docker.pkg.github.com/v2/cbws/etcd-operator/operator/manifests/v0.10.0: no basic auth credentials
```
Apparently this is a `wont-fix`: https://github.community/t5/GitHub-Actions/docker-pull-from-public-GitHub-Package-Registry-fail-with-quot/m-p/32888#M1294

Do you have any to to push to a public repo (Docker Hub would do), or would you accept a patch?

Thanks

**Comment by Marlinc** [comment]
Hey @croomes,

Thanks for checking out the fork!

Yes we know.. this is very unfortunate issue. We can definitely look into using Docker Hub, we ran into this issue on our side as well.

I'll do some research on this, could you in the mean time push the package to a private registry so you won't be blocked by this?

**Comment by Marlinc** [comment]
Hey there,

I have just pushed the release to https://hub.docker.com/r/cbws/etcd-operator/tags

**Comment by croomes** [comment]
Thanks, works great!
